name = "Hydrographs"
uuid = "b8148ea3-0609-4e06-811a-0cc0e815f0cc"
authors = ["Peter Shin <petershintech@gmail.com>"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
VegaLite = "112f6efa-9a02-5b7d-90c0-432ed331239a"

[compat]
DataFrames = "0.21"
VegaLite = "1.0"
julia = "1.5"
